# Site settings
title: 2030 Watch
url: http://2030-watch.de
staticurl: /static/

contact:
  - mail: 2030-Watch@okfn.de
  - phone: "+49 30 57703666-0"
  - fax: "Fax: +49 30 57703666-9"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF6640
  primary-rgb: "255,102,64" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/2030WatchDe
  - title: github
    url: https://github.com/okfde/2030-watch.de

# Postal address (add as many lines as necessary)
address:
  - line: Open Knowledge Foundation Deutschland e.V.
  - line: Singerstr. 109, 10179 Berlin, Deutschland

organisation:
  - line: "Vereinsregister Nr: VR 30468 B"
  - line: "Steuernummer: 27/674/52428"
  - line: "VAT: DE278022128"

# Build settings
markdown: kramdown
permalink: pretty

paginate: 8
paginate_path: blog/page/:num/

gems: [jekyll-paginate]

exclude: ['Gemfile*', 'CNAME', 'README.md']

sass:
  sass_dir: static/style/_sass
  style: compressed

collections:
  - sdgs

indicatorarray: []
